from setuptools import setup

setup(
    name='ikarion_data_infrastructure',
    version='0.0.1',
    packages=['venv', 'venv.Lib', 'venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib',
              'venv.Lib.collections', 'venv.Lib.site-packages', 'venv.Lib.site-packages.pip',
              'venv.Lib.site-packages.pip.req', 'venv.Lib.site-packages.pip.vcs', 'venv.Lib.site-packages.pip.utils',
              'venv.Lib.site-packages.pip.compat', 'venv.Lib.site-packages.pip.models',
              'venv.Lib.site-packages.pip._vendor', 'venv.Lib.site-packages.pip._vendor.distlib',
              'venv.Lib.site-packages.pip._vendor.distlib._backport', 'venv.Lib.site-packages.pip._vendor.colorama',
              'venv.Lib.site-packages.pip._vendor.html5lib', 'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip.commands', 'venv.Lib.site-packages.pip.operations',
              'venv.Lib.site-packages.bson', 'venv.Lib.site-packages.click', 'venv.Lib.site-packages.flask',
              'venv.Lib.site-packages.flask.ext', 'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.tool',
              'venv.Lib.site-packages.wheel.signatures', 'venv.Lib.site-packages.gridfs',
              'venv.Lib.site-packages.jinja2', 'venv.Lib.site-packages.pymongo', 'venv.Lib.site-packages.werkzeug',
              'venv.Lib.site-packages.werkzeug.debug', 'venv.Lib.site-packages.werkzeug.contrib',
              'venv.Lib.site-packages.markupsafe', 'venv.Lib.site-packages.setuptools',
              'venv.Lib.site-packages.setuptools.extern', 'venv.Lib.site-packages.setuptools.command',
              'venv.Lib.site-packages.flask_pymongo', 'venv.Lib.site-packages.pkg_resources',
              'venv.Lib.site-packages.pkg_resources.extern', 'venv.Lib.site-packages.pkg_resources._vendor',
              'venv.Lib.site-packages.pkg_resources._vendor.packaging', 'venv.Scripts', 'ikarion_data_management',
              'ikarion_data_management.test', 'ikarion_data_management.data_model_api',
              'ikarion_data_management.log_aggregator', 'ikarion_data_management.data_access_layer',
              'ikarion_data_management.data_access_layer.xapi_access_layer',
              'ikarion_data_management.data_access_layer.model_db_access_layer'],
    url='',
    license='',
    author='hecking',
    author_email='hecking@collide.info',
    description=''
)
